### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by sambnh** [Moontemple/Asteroid#10]
There should be a script which can be used to setup the SQL database, currently the program assumes that the database has been setup and matches the flask server.

**Comment by Moontemple** [comment]
i've made a small python and bash script combo which creates a blank database and adds a single test song, but to make this final it's going to need a config parser and proper config files (including for the SQLite db).

i'll make a standalone python CLT for testing and alpha purposes and push it - it will be generic enough to easily integrate into a setup routine later down the line, but i'll rely (as i have been) on environment variables for now as it's the lazy's man's configuration :p

**Comment by Moontemple** [comment]
okay, done and packaged into `run.py` with a usage print. going to mark this as done for now
