### ISSUE TITLE
Full documentation coverage

### ISSUE THREAD

**Issue by sambnh** [Moontemple/Asteroid#11]
There are many sections of code which are undocumented.
Some are highlighted with TODOs, others are not.

**Comment by Moontemple** [comment]
Python src is pretty close to being fully documented, JS however has no non-inline docs (@JrTheDragon01 said he will address this)

**Comment by Moontemple** [comment]
in c2b2b8c43e110d8f11700862b9ebcefc8a33534c updated all python documentation

**Comment by Moontemple** [comment]
all documentation now complete

**Comment by Moontemple** [comment]
@JrTheDragon01 didn't tell he hadn't finished

**Comment by JrTheDragon01** [comment]
> @JrTheDragon01 didn't tell he hadn't finished

@Moontemple assumed I'd finished when I had said nothing of the sort.
You know what they say about people who assume.

**Comment by JrTheDragon01** [comment]
Completed as of ba221acb08c0d5a5a517b7495a2a3d7f96882ebf
