### ISSUE TITLE
Song durations display bad with real data

### ISSUE THREAD

**Issue by Moontemple** [Moontemple/Asteroid#14]
Since the song durations in the database are stored as `float`, the web end should just truncate the display to a more human readable form. At the moment, displays 
`The Fourth Colour | King Gizzard & The Lizard Wizard | 6:12.445612244897973`

**Comment by JrTheDragon01** [comment]
Will sort out later today

**Comment by JrTheDragon01** [comment]
Hopefully sorted in a60a9b474c88ed0a2fd2c0d3f67b9846f9663e54. Closing for now.
