### ISSUE TITLE
Setup.py module

### ISSUE THREAD

**Issue by sambnh** [Moontemple/Asteroid#15]
There should be a setup.py module which contains the metadata about the project.
https://setuptools.readthedocs.io/en/latest/

**Comment by sambnh** [comment]
@Moontemple @JrTheDragon01 I've push a setup.py file to the issue-15 branch. I've tested out installing the program seemed good for me however it has changed a lot since I last used it, so I recommend checking it out. Just use `pip install .` instead of `pip install requirements.txt`.

**Comment by Moontemple** [comment]
merged with master
