### ISSUE TITLE
Cookies not checking against database for validity

### ISSUE THREAD

**Issue by JrTheDragon01** [Moontemple/Asteroid#16]
Clients with cookies retained upon clearing of user database still have access to everything, with errors thrown if their previous ID is o.o.b for new database.

**Comment by Moontemple** [comment]
This can be done in the JS; have a script which does a GET to ``/db/users/id={}`` and check if the user cookie id is in the database, else delete and redirect to ``/auth`` -- so going to reassign this to you.

**Comment by JrTheDragon01** [comment]
no u

**Comment by JrTheDragon01** [comment]
Fixed as of 24728f206f03be4f101e2586a30ba32123aa8f32
