### ISSUE TITLE
Quieter HTTP Chatter

### ISSUE THREAD

**Issue by Moontemple** [Moontemple/Asteroid#23]
as of 0de8a66ccd598a2063f7db5dacbe97e886433d98 there are now new query endpoints for the music database, namely ``/db/music?name={}``  and ``/db/music?artist={}`` which will use the sql language to query for substrings (in theory, this is less process intensive on the python end too) -- instead of having to query the whole database and then sort in JS when someone searches, you can now just query their search string.

**Comment by JrTheDragon01** [comment]
Working on this now - calling to ``/db/music?page=n`` for the main 'downloaded' tab and using ``/db/music?name={}&artist={}`` for searches

**Comment by JrTheDragon01** [comment]
@Moontemple can we also have a endpoint for multiple songs by id e.g ``/db/music?id={id1}%20{id2}`` usw.

**Comment by JrTheDragon01** [comment]
Now sorted
