### ISSUE TITLE
YouTube searches

### ISSUE THREAD

**Issue by Moontemple** [Moontemple/Asteroid#24]
Get the JS to search with the YouTube API (if it exists) to query songs and provide a request button for each.

**Comment by sambnh** [comment]
https://github.com/youtube/api-samples contains examples of the youtube api

**Comment by JrTheDragon01** [comment]
Using the API to query songs requires youtube authentication and takes up 'quota points' on a per-search basis; such that we would be limited to 100 searches per day. This is too few for our purposes; closing this issue for now as seems to not be worth it.
