### ISSUE TITLE
Sanitise SQL to prevent SQL injection

### ISSUE THREAD

**Issue by sambnh** [Moontemple/Asteroid#3]
It is currently possible to inject SQL using post requests.
This can be avoided by sanitising SQL before querying the database.

**Comment by Moontemple** [comment]
Fixed for the database classes in 0de8a66ccd598a2063f7db5dacbe97e886433d98 using decorators on functions handling user data.

Fixed for the init database building in e0ac1964303b6f692c8e6f06b1b512ae8fc195ea by making a function call to clean song names, paths, and artists.

Noticed a new bug, namely if song has no meta data  when being added to database, raises exception and as such fails to add the song. Have opened a  separate issue for this ( Issue #22 ).
