### ISSUE TITLE
Unify versioning

### ISSUE THREAD

**Issue by sambnh** [Moontemple/Asteroid#6]
The version is displayed as different versions in different locations.
All versions should be the same, which can be achieved by storing the version in a single location and reference it everywhere else.

**Comment by JrTheDragon01** [comment]
HTML version no. updated in 9af4ffb233102efd52d9f4e91e7c09ebe846ad9d ; not sure if that is all of the occurences.

**Comment by JrTheDragon01** [comment]
@sambnh if you could let me know whether there are more occurrences of version numbering that I will be able to locate and change that you know of, or whether there aren't, and I can therefore close this issue (for now, until any more happen to pop up)

that'd be great

**Comment by sambnh** [comment]
@JrTheDragon01 I'll take a look myself today and try and find the other version number I found yesterday
