### ISSUE TITLE
Change table class names for clarity

### ISSUE THREAD

**Issue by sambnh** [Moontemple/Asteroid#7]
Classes representing tables are referred to as 'MusicDB' implying they are databases.
For clarity these classes should be renamed to more relevant names.

**Comment by Moontemple** [comment]
i'm going to leave them named how they are at the moment, since there is the option to separate databases for users and music which alleviates said ambiguity -- likewise, they both inherit/use the database instance as a metaclass, so sort of are databases? ?:~j
